server {
    listen 80;
    server_name contoh-nusantara.local localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Sengaja TIDAK memblokir file .bak atau folder /internal/ secara server-side,
    # supaya latihan OSINT (menemukan file lewat robots.txt) benar-benar berhasil.
    # Di dunia nyata, ini justru contoh kesalahan konfigurasi yang sering terjadi.

    location / {
        try_files $uri $uri/ =404;
    }
}
