[global]
workgroup = WORKGROUP
security = user
map to guest = bad user
access based share enum = yes

# Audit logging
logging = syslog@1 file
syslog = 1
vfs objects = full_audit
full_audit:prefix = AUDIT | %u | %S
full_audit:success = connect pwrite
full_audit:failure = all
full_audit:facility = local5
full_audit:priority = notice

[ebooks]
path = /libraryit/ebooks
valid users = @staff, @readonly
write list = @staff
browseable = yes

[papers]
path = /libraryit/papers
valid users = @staff, @readonly
write list = @staff
browseable = yes

[sourcecode]
path = /libraryit/sourcecode
valid users = @staff
write list = @staff
browseable = yes

[docs]
path = /libraryit/docs
valid users = @staff, @readonly
write list = librarian
browseable = yes
